title:             Una Educación para el Siglo XXI
subtitle:          Miradas desde las Ciencias y las Artes
description:       V Jornadas 2019
email:             jornadassiglo21@gmail.com
navigationTitle:   Inicio
author:            Educación Siglo XXI

# Social Profiles
twitter_username:  EDUCACION_SXXI
github_username:   EducacionSiglo21
facebook_username: laeducaciondelsigloXXI

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
